create table if not exists contact_messages (
  id bigint generated by default as identity primary key,
  username text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table contact_messages enable row level security;

drop policy if exists "Anyone can insert contact messages" on contact_messages;
create policy "Anyone can insert contact messages"
on contact_messages
for insert
to anon
with check (true);

drop policy if exists "Anyone can read contact messages" on contact_messages;
create policy "Anyone can read contact messages"
on contact_messages
for select
to anon
using (true);

drop policy if exists "Anyone can delete contact messages" on contact_messages;
create policy "Anyone can delete contact messages"
on contact_messages
for delete
to anon
using (true);
